#!/usr/bin/env bash
# Basic setup for C/C++ dev environment
# 
# This replaces annoying git modules or some other methods of importing a project
# into a source tree.
# 
# If this repo were to change frequently, then perhaps this wouldn't be the best
# solution.

set -e

os="$(uname -s | tr 'A-Z' 'a-z')"

if [[ $os == darwin ]]; then
  command -v clang >/dev/null || sudo xcode-select --install
  command -v gcc >/dev/null || brew install gcc
  command -v cmake >/dev/null || brew install cmake
elif [[ $os == linux ]]; then
  command -v gcc || {
    sudo apt-get update -yqq
    sudo apt-get install build-essential -yqq
  }
fi

command -v cmake >/dev/null || {
  echo "Can't seem to find cmake even after an attempted install."
  echo "Please install it and retry."
  exit 1
}

[[ -d tests/googletest && -f tests/googletest/CMakeLists.txt ]] || {
  echo 'Something is missing in GoogleTest, updating...'
  rm -rf tests/googletest
  git clone https://github.com/google/googletest.git tests/googletest
}

cd tests/googletest
echo "Building GoogleTest..."
mkdir -p build
cd build
echo "Configuring and building GoogleTest..."
cmake .. && make -j 4
echo "———————————————————————————————————————————————————————————"
echo -e "\033[1;32mGoogleTest setup complete!\033[0m"
echo
echo -e "You can now build the project using:"
echo
echo -e "  \033[0;33mmake                 \033[1;30m# Traditional Make build\033[0m"
echo -e "  \033[0;33mmake cmake-build     \033[1;30m# CMake build\033[0m"
echo -e "  \033[0;33mmake test            \033[1;30m# Run tests with Make\033[0m"
echo -e "  \033[0;33mmake cmake-test      \033[1;30m# Run tests with CMake\033[0m"

