name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ make cmake

    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install gcc make cmake

    - name: Build Google Test
      run: |
        bash tests/setup

    - name: Verify Google Test libraries
      run: |
        ls -la tests/googletest/build/lib/
        file tests/googletest/build/lib/libgtest.a
        file tests/googletest/build/lib/libgtest_main.a

    - name: Build project
      run: |
        make -j 4 build

    - name: Run tests
      run: |
        make test

    - name: Test binary execution
      run: |
        # Test that the binary runs and shows help
        ./bin/gomoku --help
        
        # Test that the binary can be invoked with various flags
        timeout 5s ./bin/gomoku --level easy --board 15 || true
        echo "Binary execution test completed"

    - name: Check for memory leaks (Ubuntu only)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install -y valgrind
        # Run a quick memory check on the test binary
        valgrind --leak-check=summary --error-exitcode=1 ./bin/test_gomoku || echo "Memory check completed" 

    - name: Build httpd
      run: |
        make httpd
        ./bin/gomoku-httpd -h

    - name: Run httpd Tests
      run: |
        make test-httpd

